language: python
cache: pip
python:
  - "3.7"
  - "3.8"

before_script:
  - sudo apt-get install -y p7zip-full
  - make config

script:
  - tox -e lint
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then tox -e py38; else tox -e py37; fi
  - make build

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then ./ci_publish.sh ; fi

notifications:
  email:
    on_success: never
    on_failure: change
