language: python
cache: pip
python:
  - "3.6"
  - "3.7"

before_script:
  - sudo apt-get install -y p7zip-full
  - make config

script:
  - tox -e lint
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then tox -e py36; else tox -e py37; fi
  - make build

after_success:
  - ./ci_publish.sh

notifications:
  email:
    on_success: never
    on_failure: change