language: python
cache: pip
python:
  - "3.7"

before_script:
  - sudo apt-get install -y p7zip-full
  - make config

script:
  - make test
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make publish
    fi

notifications:
  email:
    on_success: never
    on_failure: change